import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "../globals.css";
import AppClientProvider from "@/providers/AppClientProvider";
import AppQueryProvider from "@/providers/ReactQueryProvider";
import { getStaticParams } from "@/locales/server";

const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hospitalia | Home",
  description: "Generated by Dhrubok",
};

export function generateStaticParams() {
  return getStaticParams();
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body
        className={`${PlusJakartaSans.variable} ${inter.variable} antialiased`}
      >
        <AppClientProvider locale={locale || "en"}>
          <AppQueryProvider>{children}</AppQueryProvider>
        </AppClientProvider>
      </body>
    </html>
  );
}
